/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    posts: Post;
    users: User;
    media: Media;
    profiles: Profile;
    skills: Skill;
  };
  globals: {};
}
export interface Post {
  id: string;
  title: string;
  description: string;
  keywords?: string;
  postImage: string | Media;
  content?: {
    [k: string]: unknown;
  }[];
  status?: 'draft' | 'published';
  publishedDate?: string;
  author?: string | User;
  updatedAt: string;
  createdAt: string;
}
export interface Media {
  id: string;
  alt?: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  sizes?: {
    thumbnail?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    sixteenByNineMedium?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
  };
}
export interface User {
  id: string;
  name?: string;
  roles?: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Profile {
  id: string;
  name: string;
  description: string;
  skills?: string[] | Skill[];
  updatedAt: string;
  createdAt: string;
}
export interface Skill {
  id: string;
  name?: string;
}
